console.log("Hello world!")
var foodItems = [
  { id: 101, category: 'main-dish' ,item: 'Classic Burger', price: '$12', img: 'Classic_Burger.png'},
  { id: 102, category: 'main-dish' ,item: 'BBQ Bacon Burger',  price: '$15', img: 'BBQ_Bacon_Burger.png'},
  { id: 103, category: 'main-dish' ,item: 'Crispy Chicken Burger', price: '$14', img: 'Crispy_Chicken_Burger.png'},
  { id: 104, category: 'main-dish' ,item: 'Loaded Fries', price: '$10', img: 'Loaded_Fries.png'},
  { id: 105, category: 'main-dish' ,item: 'Hot Dog', price: '$9', img: 'Hot_Dog.png'},
  { id: 106, category: 'main-dish' ,item: 'Taco Trio', price: '$13', img: 'Taco_Trio.png'},
  { id: 107, category: 'Sides' ,item: 'French Fries', price: '$5', img: 'French_Fries.png'},
  { id: 108, category: 'Sides' ,item: 'Curly Fries', price: '$6', img: 'Curly_Fries.png'},
  { id: 109, category: 'Sides' ,item: 'Onion Rings', price: '$6', img: 'Onion_Rings.png'},
  { id: 110, category: 'Sides' ,item: 'Mozzarella Sticks', price: '$7', img: 'Mozzarella_Sticks.png'},
  { id: 111, category: 'Sides' ,item: 'Garlic Bread', price: '$5', img: 'Garlic_Bread.png'},
  { id: 112, category: 'Drinks' ,item: 'Cola', price: '$4', img: 'Cola.png'},
  { id: 113, category: 'Drinks' ,item: 'Lemonade', price: '$4', img: 'Lemonade.png'},
  { id: 114, category: 'Drinks' ,item: 'Iced Coffee', price: '$6', img: 'Iced_Coffee.png'},
  { id: 115, category: 'Drinks' ,item: 'Milkshake', price: '$7', img: 'Milkshake.png'},
  { id: 116, category: 'Drinks' ,item: 'Fruit Smoothie', price: '$4', img: 'Fruit_Smoothie.png'},
  { id: 117, category: 'Desserts' ,item: 'Brownie', price: '$5', img: 'Brownie.png'},
  { id: 118, category: 'Desserts' ,item: 'Donut', price: '$4', img: 'Donut.png'},
  { id: 119, category: 'Desserts' ,item: 'Churros', price: '$6', img: 'Churros.png'},
  { id: 120, category: 'Desserts' ,item: 'Ice Cream Cup', price: '$5', img: 'Ice_Cream_Cup.png'},
  { id: 121, category: 'Desserts' ,item: 'Cookie', price: '$3', img: 'Cookie.png'},
];